# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "news4p-terraform-state"
    key     = "rag-patform/utils/terraform.tfstate"
    profile = "news4p"
    region  = "eu-south-1"
  }
}
