# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "eu-south-1"
  profile = "news4p"
  default_tags {
    tags = {
      PROJECT   = "POC"
      Terraform = "true"
    }
  }
}


