# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "riassume-state-bucket"
    key     = "news4p/terraform.tfstate"
    profile = "work_us"
    region  = "us-east-1"
  }
}
