# # Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# terraform {
#   backend "s3" {
#     bucket  = "news4p-terraform-state"
#     key     = "news4p/cdn/terraform.tfstate"
#     profile = "work_us"
#     region  = "us-east-1"
#   }
# }
